using Moq;
using Rok.Application.Features.Playlists.Requests;
using Rok.Application.Interfaces.Repositories;
using Rok.Shared.Enums;

namespace Rok.ApplicationTests.Features.Playlists.Requests;

public class GetPlaylistByIdRequestHandlerTests
{
    [Fact(DisplayName = "Handle should return mapped playlist when playlist exists")]
    public async Task Handle_ShouldReturnMappedPlaylist_WhenPlaylistExists()
    {
        // Arrange
        PlaylistHeaderEntity entity = new() { Id = 3, Name = "Favs" };
        Mock<IPlaylistHeaderRepository> repository = new();
        repository.Setup(r => r.GetByIdAsync(3, It.IsAny<RepositoryConnectionKind>())).ReturnsAsync(entity);
        GetPlaylistByIdRequestHandler handler = new(repository.Object);

        // Act
        Result<PlaylistHeaderDto> result = await handler.Handle(new GetPlaylistByIdRequest(3), CancellationToken.None);

        // Assert
        Assert.True(result.IsSuccess);
        Assert.Equal("Favs", result.Value.Name);
    }

    [Fact(DisplayName = "Handle should return NotFound failure when playlist does not exist")]
    public async Task Handle_ShouldReturnNotFoundFailure_WhenPlaylistDoesNotExist()
    {
        // Arrange
        Mock<IPlaylistHeaderRepository> repository = new();
        repository.Setup(r => r.GetByIdAsync(It.IsAny<long>(), It.IsAny<RepositoryConnectionKind>())).ReturnsAsync((PlaylistHeaderEntity?)null);
        GetPlaylistByIdRequestHandler handler = new(repository.Object);

        // Act
        Result<PlaylistHeaderDto> result = await handler.Handle(new GetPlaylistByIdRequest(99), CancellationToken.None);

        // Assert
        Assert.True(result.IsFailure);
        Assert.IsType<NotFoundError>(result.Errors[0]);
        Assert.Equal("playlist.not_found", result.Errors[0].Code);
    }
}

public class GetAllPlaylistsRequestHandlerTests
{
    [Fact(DisplayName = "Handle should return all mapped playlists when no filter is applied")]
    public async Task Handle_ShouldReturnAllMappedPlaylists_WhenNoFilterIsApplied()
    {
        // Arrange
        List<PlaylistHeaderEntity> playlists = new()
        {
            new() { Id = 1, Name = "P1", Type = 0 },
            new() { Id = 2, Name = "P2", Type = 1 }
        };
        Mock<IPlaylistHeaderRepository> repository = new();
        repository.Setup(r => r.GetAllAsync(It.IsAny<RepositoryConnectionKind>())).ReturnsAsync(playlists);
        GetAllPlaylistsRequestHandler handler = new(repository.Object);

        // Act
        IEnumerable<PlaylistHeaderDto> result = await handler.Handle(new GetAllPlaylistsRequest(), CancellationToken.None);

        // Assert
        Assert.Equal(2, result.Count());
    }

    [Fact(DisplayName = "Handle should filter playlists by type when filter is provided")]
    public async Task Handle_ShouldFilterPlaylistsByType_WhenFilterIsProvided()
    {
        // Arrange
        List<PlaylistHeaderEntity> playlists = new()
        {
            new() { Id = 1, Name = "Smart", Type = (int)PlaylistType.Smart },
            new() { Id = 2, Name = "Classic", Type = (int)PlaylistType.Classic }
        };
        Mock<IPlaylistHeaderRepository> repository = new();
        repository.Setup(r => r.GetAllAsync(It.IsAny<RepositoryConnectionKind>())).ReturnsAsync(playlists);
        GetAllPlaylistsRequestHandler handler = new(repository.Object);

        // Act
        IEnumerable<PlaylistHeaderDto> result = await handler.Handle(new GetAllPlaylistsRequest { FilterType = PlaylistType.Classic }, CancellationToken.None);

        // Assert
        PlaylistHeaderDto dto = Assert.Single(result);
        Assert.Equal("Classic", dto.Name);
    }
}

public class GeneratePlaylistTracksRequestHandlerTests
{
    [Fact(DisplayName = "Handle should return tracks generated by repository mapped to DTOs")]
    public async Task Handle_ShouldReturnTracksGeneratedByRepository_MappedToDtos()
    {
        // Arrange
        List<TrackEntity> tracks = new()
        {
            new() { Id = 1, Title = "T1", ArtistId = 1 },
            new() { Id = 2, Title = "T2", ArtistId = 2 }
        };
        Mock<IPlaylistTrackGenerateRepository> repository = new();
        repository.Setup(r => r.GenerateAsync(It.IsAny<GeneratePlaylistTracksRequest>(), It.IsAny<RepositoryConnectionKind>())).ReturnsAsync(tracks);
        GeneratePlaylistTracksRequestHandler handler = new(repository.Object);

        GeneratePlaylistTracksRequest query = new()
        {
            PlaylistTrackCount = 2,
            Group = new PlaylistGroupDto { Name = "G" }
        };

        // Act
        IEnumerable<TrackDto> result = await handler.Handle(query, CancellationToken.None);

        // Assert
        Assert.Equal(2, result.Count());
    }
}
