#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Running build...'
dotnet husky run --name dotnet-build

echo 'Formatting staged files...'
dotnet husky run --name dotnet-format-staged-files

echo 'Completed pre-commit changes'